# Generated by Django 5.2.7 on 2025-10-31 16:19

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, validators=[usuarios.models.validator])),
                ('nombre_negocio', models.CharField(db_column='nombre_negocio', max_length=200, unique=True, validators=[usuarios.models.validator])),
                ('correo', models.EmailField(db_column='correo', max_length=254, unique=True, validators=[usuarios.models.validator])),
                ('contrasena', models.CharField(db_column='contrasena', default='defaultpassword', max_length=128, validators=[usuarios.models.validator])),
                ('telefono', models.CharField(db_column='telefono', max_length=10, unique=True, validators=[usuarios.models.validator])),
                ('direccion', models.CharField(db_column='direccion', max_length=255, validators=[usuarios.models.validator])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('usuario', models.CharField(db_column='usuario', max_length=50, unique=True, validators=[usuarios.models.validator])),
                ('estado', models.BooleanField(db_column='estado', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIOS',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
