# Generated by Django 5.2.7 on 2025-11-02 14:57

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(db_column='correo', max_length=254, unique=True, validators=[usuarios.models.validator], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(db_column='direccion', max_length=255, validators=[usuarios.models.validator], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_registro', verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_negocio',
            field=models.CharField(db_column='nombre_negocio', max_length=200, unique=True, validators=[usuarios.models.validator], verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(db_column='telefono', max_length=10, unique=True, validators=[usuarios.models.validator], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(db_column='usuario', max_length=50, unique=True, validators=[usuarios.models.validator], verbose_name='Nombre de Usuario'),
        ),
    ]
