# Generated by Django 5.2.7 on 2025-11-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_contrasena_remove_usuario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(db_column='estado', default=True, verbose_name='Cuenta Activa'),
        ),
    ]
