# Generated by Django 5.2.7 on 2025-11-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
