# Generated by Django 5.2.7 on 2025-11-04 14:00

import django.db.models.deletion
import productos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[productos.models.validator])),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'CATEGORIAS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(db_column='nombre', max_length=100, validators=[productos.models.validator], verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(db_column='descripcion', validators=[productos.models.validator], verbose_name='Descripción del Producto')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10, validators=[productos.models.validator], verbose_name='Precio del Producto')),
                ('cantidad', models.IntegerField(db_column='cantidad', validators=[productos.models.validator], verbose_name='Cantidad del Producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vendido', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], db_column='estado', default='Nuevo', max_length=20, verbose_name='Estado del Producto')),
                ('vendido', models.BooleanField(db_column='vendido', default=False, verbose_name='Producto Vendido')),
                ('imagen', models.ImageField(blank=True, db_column='imagen', null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='productos.categoria', verbose_name='ID Categoria')),
                ('id_negocio', models.ForeignKey(db_column='id_negocio', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL, verbose_name='ID Negocio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_url', models.URLField(db_column='imagen_url', help_text='URL de Supabase Storage', max_length=500, verbose_name='URL de la Imagen')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen Producto',
                'verbose_name_plural': 'Imagenes Productos',
                'db_table': 'IMAGENES_PRODUCTOS',
                'ordering': ['id_producto'],
            },
        ),
    ]
