# Generated by Django 5.2.7 on 2025-11-05 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto', verbose_name='ID Producto'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='PRODUCTOS',
        ),
    ]
