# Generated by Django 5.2.7 on 2025-11-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen_url',
            field=models.ImageField(db_column='imagen_url', help_text='URL de Supabase Storage', max_length=500, upload_to='', verbose_name='URL de la Imagen'),
        ),
    ]
